# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dudi/DevArea/MesosBenchMark

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dudi/DevArea/MesosBenchMark

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dudi/DevArea/MesosBenchMark/CMakeFiles /home/dudi/DevArea/MesosBenchMark/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dudi/DevArea/MesosBenchMark/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MesosBenchMark

# Build rule for target.
MesosBenchMark: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MesosBenchMark
.PHONY : MesosBenchMark

# fast build rule for target.
MesosBenchMark/fast:
	$(MAKE) -f CMakeFiles/MesosBenchMark.dir/build.make CMakeFiles/MesosBenchMark.dir/build
.PHONY : MesosBenchMark/fast

#=============================================================================
# Target rules for targets named PROTO_BUILD

# Build rule for target.
PROTO_BUILD: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PROTO_BUILD
.PHONY : PROTO_BUILD

# fast build rule for target.
PROTO_BUILD/fast:
	$(MAKE) -f CMakeFiles/PROTO_BUILD.dir/build.make CMakeFiles/PROTO_BUILD.dir/build
.PHONY : PROTO_BUILD/fast

#=============================================================================
# Target rules for targets named Core

# Build rule for target.
Core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Core
.PHONY : Core

# fast build rule for target.
Core/fast:
	$(MAKE) -f Core/CMakeFiles/Core.dir/build.make Core/CMakeFiles/Core.dir/build
.PHONY : Core/fast

#=============================================================================
# Target rules for targets named ClusterManager

# Build rule for target.
ClusterManager: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ClusterManager
.PHONY : ClusterManager

# fast build rule for target.
ClusterManager/fast:
	$(MAKE) -f ClusterManager/CMakeFiles/ClusterManager.dir/build.make ClusterManager/CMakeFiles/ClusterManager.dir/build
.PHONY : ClusterManager/fast

#=============================================================================
# Target rules for targets named Communication

# Build rule for target.
Communication: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Communication
.PHONY : Communication

# fast build rule for target.
Communication/fast:
	$(MAKE) -f Communication/CMakeFiles/Communication.dir/build.make Communication/CMakeFiles/Communication.dir/build
.PHONY : Communication/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/MesosBenchMark.dir/build.make CMakeFiles/MesosBenchMark.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/MesosBenchMark.dir/build.make CMakeFiles/MesosBenchMark.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/MesosBenchMark.dir/build.make CMakeFiles/MesosBenchMark.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MesosBenchMark"
	@echo "... PROTO_BUILD"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Core"
	@echo "... ClusterManager"
	@echo "... Communication"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

