// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClusterService.proto

#ifndef PROTOBUF_ClusterService_2eproto__INCLUDED
#define PROTOBUF_ClusterService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace ClusterService {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ClusterService_2eproto();
void protobuf_AssignDesc_ClusterService_2eproto();
void protobuf_ShutdownFile_ClusterService_2eproto();

class Empty;
class Param;
class Params;

enum AlgoType {
  Measurment = 0,
  AlgoType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  AlgoType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool AlgoType_IsValid(int value);
const AlgoType AlgoType_MIN = Measurment;
const AlgoType AlgoType_MAX = Measurment;
const int AlgoType_ARRAYSIZE = AlgoType_MAX + 1;

const ::google::protobuf::EnumDescriptor* AlgoType_descriptor();
inline const ::std::string& AlgoType_Name(AlgoType value) {
  return ::google::protobuf::internal::NameOfEnum(
    AlgoType_descriptor(), value);
}
inline bool AlgoType_Parse(
    const ::std::string& name, AlgoType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<AlgoType>(
    AlgoType_descriptor(), name, value);
}
enum ParamValueType {
  BOOL = 0,
  SHORT = 1,
  INT = 2,
  LONG = 3,
  FLOAT = 4,
  DOUBLE = 5,
  STRING = 6,
  ParamValueType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ParamValueType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ParamValueType_IsValid(int value);
const ParamValueType ParamValueType_MIN = BOOL;
const ParamValueType ParamValueType_MAX = STRING;
const int ParamValueType_ARRAYSIZE = ParamValueType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ParamValueType_descriptor();
inline const ::std::string& ParamValueType_Name(ParamValueType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ParamValueType_descriptor(), value);
}
inline bool ParamValueType_Parse(
    const ::std::string& name, ParamValueType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ParamValueType>(
    ParamValueType_descriptor(), name, value);
}
// ===================================================================

class Empty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ClusterService.Empty) */ {
 public:
  Empty();
  virtual ~Empty();

  Empty(const Empty& from);

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Empty& default_instance();

  void Swap(Empty* other);

  // implements Message ----------------------------------------------

  inline Empty* New() const { return New(NULL); }

  Empty* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Empty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ClusterService.Empty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ClusterService_2eproto();
  friend void protobuf_AssignDesc_ClusterService_2eproto();
  friend void protobuf_ShutdownFile_ClusterService_2eproto();

  void InitAsDefaultInstance();
  static Empty* default_instance_;
};
// -------------------------------------------------------------------

class Param : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ClusterService.Param) */ {
 public:
  Param();
  virtual ~Param();

  Param(const Param& from);

  inline Param& operator=(const Param& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Param& default_instance();

  void Swap(Param* other);

  // implements Message ----------------------------------------------

  inline Param* New() const { return New(NULL); }

  Param* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Param& from);
  void MergeFrom(const Param& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Param* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional int32 valueInt = 2;
  void clear_valueint();
  static const int kValueIntFieldNumber = 2;
  ::google::protobuf::int32 valueint() const;
  void set_valueint(::google::protobuf::int32 value);

  // optional int64 valueLong = 3;
  void clear_valuelong();
  static const int kValueLongFieldNumber = 3;
  ::google::protobuf::int64 valuelong() const;
  void set_valuelong(::google::protobuf::int64 value);

  // optional float valueFloat = 4;
  void clear_valuefloat();
  static const int kValueFloatFieldNumber = 4;
  float valuefloat() const;
  void set_valuefloat(float value);

  // optional double valueDouble = 5;
  void clear_valuedouble();
  static const int kValueDoubleFieldNumber = 5;
  double valuedouble() const;
  void set_valuedouble(double value);

  // optional bool valueBool = 6;
  void clear_valuebool();
  static const int kValueBoolFieldNumber = 6;
  bool valuebool() const;
  void set_valuebool(bool value);

  // optional string valueString = 7;
  void clear_valuestring();
  static const int kValueStringFieldNumber = 7;
  const ::std::string& valuestring() const;
  void set_valuestring(const ::std::string& value);
  void set_valuestring(const char* value);
  void set_valuestring(const char* value, size_t size);
  ::std::string* mutable_valuestring();
  ::std::string* release_valuestring();
  void set_allocated_valuestring(::std::string* valuestring);

  // optional .ClusterService.ParamValueType selectedParamValueType = 8;
  void clear_selectedparamvaluetype();
  static const int kSelectedParamValueTypeFieldNumber = 8;
  ::ClusterService::ParamValueType selectedparamvaluetype() const;
  void set_selectedparamvaluetype(::ClusterService::ParamValueType value);

  // @@protoc_insertion_point(class_scope:ClusterService.Param)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::int64 valuelong_;
  ::google::protobuf::int32 valueint_;
  float valuefloat_;
  double valuedouble_;
  ::google::protobuf::internal::ArenaStringPtr valuestring_;
  bool valuebool_;
  int selectedparamvaluetype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ClusterService_2eproto();
  friend void protobuf_AssignDesc_ClusterService_2eproto();
  friend void protobuf_ShutdownFile_ClusterService_2eproto();

  void InitAsDefaultInstance();
  static Param* default_instance_;
};
// -------------------------------------------------------------------

class Params : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ClusterService.Params) */ {
 public:
  Params();
  virtual ~Params();

  Params(const Params& from);

  inline Params& operator=(const Params& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Params& default_instance();

  void Swap(Params* other);

  // implements Message ----------------------------------------------

  inline Params* New() const { return New(NULL); }

  Params* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Params& from);
  void MergeFrom(const Params& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Params* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .ClusterService.AlgoType algoType = 1;
  void clear_algotype();
  static const int kAlgoTypeFieldNumber = 1;
  ::ClusterService::AlgoType algotype() const;
  void set_algotype(::ClusterService::AlgoType value);

  // repeated .ClusterService.Param genericParams = 2;
  int genericparams_size() const;
  void clear_genericparams();
  static const int kGenericParamsFieldNumber = 2;
  const ::ClusterService::Param& genericparams(int index) const;
  ::ClusterService::Param* mutable_genericparams(int index);
  ::ClusterService::Param* add_genericparams();
  ::google::protobuf::RepeatedPtrField< ::ClusterService::Param >*
      mutable_genericparams();
  const ::google::protobuf::RepeatedPtrField< ::ClusterService::Param >&
      genericparams() const;

  // @@protoc_insertion_point(class_scope:ClusterService.Params)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::RepeatedPtrField< ::ClusterService::Param > genericparams_;
  int algotype_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ClusterService_2eproto();
  friend void protobuf_AssignDesc_ClusterService_2eproto();
  friend void protobuf_ShutdownFile_ClusterService_2eproto();

  void InitAsDefaultInstance();
  static Params* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Empty

// -------------------------------------------------------------------

// Param

// optional string name = 1;
inline void Param::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Param::name() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Param::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ClusterService.Param.name)
}
inline void Param::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClusterService.Param.name)
}
inline void Param::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClusterService.Param.name)
}
inline ::std::string* Param::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ClusterService.Param.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Param::release_name() {
  // @@protoc_insertion_point(field_release:ClusterService.Param.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Param::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ClusterService.Param.name)
}

// optional int32 valueInt = 2;
inline void Param::clear_valueint() {
  valueint_ = 0;
}
inline ::google::protobuf::int32 Param::valueint() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueInt)
  return valueint_;
}
inline void Param::set_valueint(::google::protobuf::int32 value) {
  
  valueint_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueInt)
}

// optional int64 valueLong = 3;
inline void Param::clear_valuelong() {
  valuelong_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 Param::valuelong() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueLong)
  return valuelong_;
}
inline void Param::set_valuelong(::google::protobuf::int64 value) {
  
  valuelong_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueLong)
}

// optional float valueFloat = 4;
inline void Param::clear_valuefloat() {
  valuefloat_ = 0;
}
inline float Param::valuefloat() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueFloat)
  return valuefloat_;
}
inline void Param::set_valuefloat(float value) {
  
  valuefloat_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueFloat)
}

// optional double valueDouble = 5;
inline void Param::clear_valuedouble() {
  valuedouble_ = 0;
}
inline double Param::valuedouble() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueDouble)
  return valuedouble_;
}
inline void Param::set_valuedouble(double value) {
  
  valuedouble_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueDouble)
}

// optional bool valueBool = 6;
inline void Param::clear_valuebool() {
  valuebool_ = false;
}
inline bool Param::valuebool() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueBool)
  return valuebool_;
}
inline void Param::set_valuebool(bool value) {
  
  valuebool_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueBool)
}

// optional string valueString = 7;
inline void Param::clear_valuestring() {
  valuestring_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Param::valuestring() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueString)
  return valuestring_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Param::set_valuestring(const ::std::string& value) {
  
  valuestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueString)
}
inline void Param::set_valuestring(const char* value) {
  
  valuestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClusterService.Param.valueString)
}
inline void Param::set_valuestring(const char* value, size_t size) {
  
  valuestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClusterService.Param.valueString)
}
inline ::std::string* Param::mutable_valuestring() {
  
  // @@protoc_insertion_point(field_mutable:ClusterService.Param.valueString)
  return valuestring_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Param::release_valuestring() {
  // @@protoc_insertion_point(field_release:ClusterService.Param.valueString)
  
  return valuestring_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Param::set_allocated_valuestring(::std::string* valuestring) {
  if (valuestring != NULL) {
    
  } else {
    
  }
  valuestring_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), valuestring);
  // @@protoc_insertion_point(field_set_allocated:ClusterService.Param.valueString)
}

// optional .ClusterService.ParamValueType selectedParamValueType = 8;
inline void Param::clear_selectedparamvaluetype() {
  selectedparamvaluetype_ = 0;
}
inline ::ClusterService::ParamValueType Param::selectedparamvaluetype() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.selectedParamValueType)
  return static_cast< ::ClusterService::ParamValueType >(selectedparamvaluetype_);
}
inline void Param::set_selectedparamvaluetype(::ClusterService::ParamValueType value) {
  
  selectedparamvaluetype_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.selectedParamValueType)
}

// -------------------------------------------------------------------

// Params

// optional .ClusterService.AlgoType algoType = 1;
inline void Params::clear_algotype() {
  algotype_ = 0;
}
inline ::ClusterService::AlgoType Params::algotype() const {
  // @@protoc_insertion_point(field_get:ClusterService.Params.algoType)
  return static_cast< ::ClusterService::AlgoType >(algotype_);
}
inline void Params::set_algotype(::ClusterService::AlgoType value) {
  
  algotype_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Params.algoType)
}

// repeated .ClusterService.Param genericParams = 2;
inline int Params::genericparams_size() const {
  return genericparams_.size();
}
inline void Params::clear_genericparams() {
  genericparams_.Clear();
}
inline const ::ClusterService::Param& Params::genericparams(int index) const {
  // @@protoc_insertion_point(field_get:ClusterService.Params.genericParams)
  return genericparams_.Get(index);
}
inline ::ClusterService::Param* Params::mutable_genericparams(int index) {
  // @@protoc_insertion_point(field_mutable:ClusterService.Params.genericParams)
  return genericparams_.Mutable(index);
}
inline ::ClusterService::Param* Params::add_genericparams() {
  // @@protoc_insertion_point(field_add:ClusterService.Params.genericParams)
  return genericparams_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ClusterService::Param >*
Params::mutable_genericparams() {
  // @@protoc_insertion_point(field_mutable_list:ClusterService.Params.genericParams)
  return &genericparams_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ClusterService::Param >&
Params::genericparams() const {
  // @@protoc_insertion_point(field_list:ClusterService.Params.genericParams)
  return genericparams_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ClusterService

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ClusterService::AlgoType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ClusterService::AlgoType>() {
  return ::ClusterService::AlgoType_descriptor();
}
template <> struct is_proto_enum< ::ClusterService::ParamValueType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ClusterService::ParamValueType>() {
  return ::ClusterService::ParamValueType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ClusterService_2eproto__INCLUDED
