// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: ClusterService.proto
#ifndef GRPC_ClusterService_2eproto__INCLUDED
#define GRPC_ClusterService_2eproto__INCLUDED

#include "ClusterService.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace ClusterService {

class Commands GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status LoadParams(::grpc::ClientContext* context, const ::ClusterService::Params& request, ::ClusterService::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ClusterService::Empty>> AsyncLoadParams(::grpc::ClientContext* context, const ::ClusterService::Params& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ClusterService::Empty>>(AsyncLoadParamsRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ClusterService::Empty>* AsyncLoadParamsRaw(::grpc::ClientContext* context, const ::ClusterService::Params& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status LoadParams(::grpc::ClientContext* context, const ::ClusterService::Params& request, ::ClusterService::Empty* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ClusterService::Empty>> AsyncLoadParams(::grpc::ClientContext* context, const ::ClusterService::Params& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ClusterService::Empty>>(AsyncLoadParamsRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::ClusterService::Empty>* AsyncLoadParamsRaw(::grpc::ClientContext* context, const ::ClusterService::Params& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_LoadParams_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status LoadParams(::grpc::ServerContext* context, const ::ClusterService::Params* request, ::ClusterService::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_LoadParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_LoadParams() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_LoadParams() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadParams(::grpc::ServerContext* context, const ::ClusterService::Params* request, ::ClusterService::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLoadParams(::grpc::ServerContext* context, ::ClusterService::Params* request, ::grpc::ServerAsyncResponseWriter< ::ClusterService::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_LoadParams<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_LoadParams : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_LoadParams() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_LoadParams() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status LoadParams(::grpc::ServerContext* context, const ::ClusterService::Params* request, ::ClusterService::Empty* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace ClusterService


#endif  // GRPC_ClusterService_2eproto__INCLUDED
