// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClusterService.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "ClusterService.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace ClusterService {

namespace {

const ::google::protobuf::Descriptor* Empty_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Empty_reflection_ = NULL;
const ::google::protobuf::Descriptor* Param_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Param_reflection_ = NULL;
struct ParamOneofInstance {
  ::google::protobuf::int32 valueint_;
  ::google::protobuf::int64 valuelong_;
  float valuefloat_;
  double valuedouble_;
  bool valuebool_;
  ::google::protobuf::internal::ArenaStringPtr valuestring_;
}* Param_default_oneof_instance_ = NULL;
const ::google::protobuf::EnumDescriptor* Param_ValueType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* Params_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Params_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* AlgoType_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_ClusterService_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_ClusterService_2eproto() {
  protobuf_AddDesc_ClusterService_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "ClusterService.proto");
  GOOGLE_CHECK(file != NULL);
  Empty_descriptor_ = file->message_type(0);
  static const int Empty_offsets_[1] = {
  };
  Empty_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Empty_descriptor_,
      Empty::default_instance_,
      Empty_offsets_,
      -1,
      -1,
      -1,
      sizeof(Empty),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Empty, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Empty, _is_default_instance_));
  Param_descriptor_ = file->message_type(1);
  static const int Param_offsets_[10] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Param_default_oneof_instance_, valueint_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Param_default_oneof_instance_, valuelong_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Param_default_oneof_instance_, valuefloat_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Param_default_oneof_instance_, valuedouble_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Param_default_oneof_instance_, valuebool_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Param_default_oneof_instance_, valuestring_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, valuestringcollection_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, valueOneOf_),
  };
  Param_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Param_descriptor_,
      Param::default_instance_,
      Param_offsets_,
      -1,
      -1,
      -1,
      Param_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, _oneof_case_[0]),
      sizeof(Param),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Param, _is_default_instance_));
  Param_ValueType_descriptor_ = Param_descriptor_->enum_type(0);
  Params_descriptor_ = file->message_type(2);
  static const int Params_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, algotype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, genericparams_),
  };
  Params_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Params_descriptor_,
      Params::default_instance_,
      Params_offsets_,
      -1,
      -1,
      -1,
      sizeof(Params),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Params, _is_default_instance_));
  AlgoType_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_ClusterService_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Empty_descriptor_, &Empty::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Param_descriptor_, &Param::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Params_descriptor_, &Params::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_ClusterService_2eproto() {
  delete Empty::default_instance_;
  delete Empty_reflection_;
  delete Param::default_instance_;
  delete Param_default_oneof_instance_;
  delete Param_reflection_;
  delete Params::default_instance_;
  delete Params_reflection_;
}

void protobuf_AddDesc_ClusterService_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_ClusterService_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024ClusterService.proto\022\016ClusterService\"\007"
    "\n\005Empty\"\245\002\n\005Param\022\022\n\010valueInt\030\001 \001(\005H\000\022\023\n"
    "\tvalueLong\030\002 \001(\003H\000\022\024\n\nvalueFloat\030\003 \001(\002H\000"
    "\022\025\n\013valueDouble\030\004 \001(\001H\000\022\023\n\tvalueBool\030\005 \001"
    "(\010H\000\022\025\n\013valueString\030\006 \001(\tH\000\022-\n\004type\030\007 \001("
    "\0162\037.ClusterService.Param.ValueType\022\014\n\004na"
    "me\030\010 \001(\t\022\035\n\025valueStringCollection\030\t \003(\t\""
    "0\n\tValueType\022\r\n\tPrimitive\020\000\022\024\n\020StringCol"
    "lection\020\001B\014\n\nvalueOneOf\"b\n\006Params\022*\n\010alg"
    "oType\030\001 \001(\0162\030.ClusterService.AlgoType\022,\n"
    "\rgenericParams\030\002 \003(\0132\025.ClusterService.Pa"
    "ram*\032\n\010AlgoType\022\016\n\nMeasurment\020\0002I\n\010Comma"
    "nds\022=\n\nLoadParams\022\026.ClusterService.Param"
    "s\032\025.ClusterService.Empty\"\000b\006proto3", 554);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ClusterService.proto", &protobuf_RegisterTypes);
  Empty::default_instance_ = new Empty();
  Param::default_instance_ = new Param();
  Param_default_oneof_instance_ = new ParamOneofInstance();
  Params::default_instance_ = new Params();
  Empty::default_instance_->InitAsDefaultInstance();
  Param::default_instance_->InitAsDefaultInstance();
  Params::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_ClusterService_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_ClusterService_2eproto {
  StaticDescriptorInitializer_ClusterService_2eproto() {
    protobuf_AddDesc_ClusterService_2eproto();
  }
} static_descriptor_initializer_ClusterService_2eproto_;
const ::google::protobuf::EnumDescriptor* AlgoType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AlgoType_descriptor_;
}
bool AlgoType_IsValid(int value) {
  switch(value) {
    case 0:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Empty::Empty()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ClusterService.Empty)
}

void Empty::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Empty::Empty(const Empty& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ClusterService.Empty)
}

void Empty::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
}

Empty::~Empty() {
  // @@protoc_insertion_point(destructor:ClusterService.Empty)
  SharedDtor();
}

void Empty::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Empty::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Empty::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Empty_descriptor_;
}

const Empty& Empty::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClusterService_2eproto();
  return *default_instance_;
}

Empty* Empty::default_instance_ = NULL;

Empty* Empty::New(::google::protobuf::Arena* arena) const {
  Empty* n = new Empty;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Empty::Clear() {
// @@protoc_insertion_point(message_clear_start:ClusterService.Empty)
}

bool Empty::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ClusterService.Empty)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
  handle_unusual:
    if (tag == 0 ||
        ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      goto success;
    }
    DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
  }
success:
  // @@protoc_insertion_point(parse_success:ClusterService.Empty)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ClusterService.Empty)
  return false;
#undef DO_
}

void Empty::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ClusterService.Empty)
  // @@protoc_insertion_point(serialize_end:ClusterService.Empty)
}

::google::protobuf::uint8* Empty::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClusterService.Empty)
  // @@protoc_insertion_point(serialize_to_array_end:ClusterService.Empty)
  return target;
}

int Empty::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ClusterService.Empty)
  int total_size = 0;

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Empty::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ClusterService.Empty)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Empty* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Empty>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ClusterService.Empty)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ClusterService.Empty)
    MergeFrom(*source);
  }
}

void Empty::MergeFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ClusterService.Empty)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
}

void Empty::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ClusterService.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Empty::CopyFrom(const Empty& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClusterService.Empty)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Empty::IsInitialized() const {

  return true;
}

void Empty::Swap(Empty* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Empty::InternalSwap(Empty* other) {
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Empty::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Empty_descriptor_;
  metadata.reflection = Empty_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Empty

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

const ::google::protobuf::EnumDescriptor* Param_ValueType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Param_ValueType_descriptor_;
}
bool Param_ValueType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Param_ValueType Param::Primitive;
const Param_ValueType Param::StringCollection;
const Param_ValueType Param::ValueType_MIN;
const Param_ValueType Param::ValueType_MAX;
const int Param::ValueType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Param::kValueIntFieldNumber;
const int Param::kValueLongFieldNumber;
const int Param::kValueFloatFieldNumber;
const int Param::kValueDoubleFieldNumber;
const int Param::kValueBoolFieldNumber;
const int Param::kValueStringFieldNumber;
const int Param::kTypeFieldNumber;
const int Param::kNameFieldNumber;
const int Param::kValueStringCollectionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Param::Param()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ClusterService.Param)
}

void Param::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  Param_default_oneof_instance_->valueint_ = 0;
  Param_default_oneof_instance_->valuelong_ = GOOGLE_LONGLONG(0);
  Param_default_oneof_instance_->valuefloat_ = 0;
  Param_default_oneof_instance_->valuedouble_ = 0;
  Param_default_oneof_instance_->valuebool_ = false;
  Param_default_oneof_instance_->valuestring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Param::Param(const Param& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ClusterService.Param)
}

void Param::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_valueOneOf();
}

Param::~Param() {
  // @@protoc_insertion_point(destructor:ClusterService.Param)
  SharedDtor();
}

void Param::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_valueOneOf()) {
    clear_valueOneOf();
  }
  if (this != default_instance_) {
  }
}

void Param::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Param::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Param_descriptor_;
}

const Param& Param::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClusterService_2eproto();
  return *default_instance_;
}

Param* Param::default_instance_ = NULL;

Param* Param::New(::google::protobuf::Arena* arena) const {
  Param* n = new Param;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Param::clear_valueOneOf() {
// @@protoc_insertion_point(one_of_clear_start:ClusterService.Param)
  switch(valueOneOf_case()) {
    case kValueInt: {
      // No need to clear
      break;
    }
    case kValueLong: {
      // No need to clear
      break;
    }
    case kValueFloat: {
      // No need to clear
      break;
    }
    case kValueDouble: {
      // No need to clear
      break;
    }
    case kValueBool: {
      // No need to clear
      break;
    }
    case kValueString: {
      valueOneOf_.valuestring_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case VALUEONEOF_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = VALUEONEOF_NOT_SET;
}


void Param::Clear() {
// @@protoc_insertion_point(message_clear_start:ClusterService.Param)
  type_ = 0;
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  valuestringcollection_.Clear();
  clear_valueOneOf();
}

bool Param::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ClusterService.Param)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 valueInt = 1;
      case 1: {
        if (tag == 8) {
          clear_valueOneOf();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &valueOneOf_.valueint_)));
          set_has_valueint();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_valueLong;
        break;
      }

      // optional int64 valueLong = 2;
      case 2: {
        if (tag == 16) {
         parse_valueLong:
          clear_valueOneOf();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &valueOneOf_.valuelong_)));
          set_has_valuelong();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_valueFloat;
        break;
      }

      // optional float valueFloat = 3;
      case 3: {
        if (tag == 29) {
         parse_valueFloat:
          clear_valueOneOf();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &valueOneOf_.valuefloat_)));
          set_has_valuefloat();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_valueDouble;
        break;
      }

      // optional double valueDouble = 4;
      case 4: {
        if (tag == 33) {
         parse_valueDouble:
          clear_valueOneOf();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &valueOneOf_.valuedouble_)));
          set_has_valuedouble();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_valueBool;
        break;
      }

      // optional bool valueBool = 5;
      case 5: {
        if (tag == 40) {
         parse_valueBool:
          clear_valueOneOf();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &valueOneOf_.valuebool_)));
          set_has_valuebool();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_valueString;
        break;
      }

      // optional string valueString = 6;
      case 6: {
        if (tag == 50) {
         parse_valueString:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_valuestring()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->valuestring().data(), this->valuestring().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ClusterService.Param.valueString"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_type;
        break;
      }

      // optional .ClusterService.Param.ValueType type = 7;
      case 7: {
        if (tag == 56) {
         parse_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::ClusterService::Param_ValueType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_name;
        break;
      }

      // optional string name = 8;
      case 8: {
        if (tag == 66) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ClusterService.Param.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_valueStringCollection;
        break;
      }

      // repeated string valueStringCollection = 9;
      case 9: {
        if (tag == 74) {
         parse_valueStringCollection:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_valuestringcollection()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->valuestringcollection(this->valuestringcollection_size() - 1).data(),
            this->valuestringcollection(this->valuestringcollection_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ClusterService.Param.valueStringCollection"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_valueStringCollection;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ClusterService.Param)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ClusterService.Param)
  return false;
#undef DO_
}

void Param::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ClusterService.Param)
  // optional int32 valueInt = 1;
  if (has_valueint()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->valueint(), output);
  }

  // optional int64 valueLong = 2;
  if (has_valuelong()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->valuelong(), output);
  }

  // optional float valueFloat = 3;
  if (has_valuefloat()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->valuefloat(), output);
  }

  // optional double valueDouble = 4;
  if (has_valuedouble()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->valuedouble(), output);
  }

  // optional bool valueBool = 5;
  if (has_valuebool()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->valuebool(), output);
  }

  // optional string valueString = 6;
  if (has_valuestring()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->valuestring().data(), this->valuestring().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ClusterService.Param.valueString");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->valuestring(), output);
  }

  // optional .ClusterService.Param.ValueType type = 7;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      7, this->type(), output);
  }

  // optional string name = 8;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ClusterService.Param.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->name(), output);
  }

  // repeated string valueStringCollection = 9;
  for (int i = 0; i < this->valuestringcollection_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->valuestringcollection(i).data(), this->valuestringcollection(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ClusterService.Param.valueStringCollection");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      9, this->valuestringcollection(i), output);
  }

  // @@protoc_insertion_point(serialize_end:ClusterService.Param)
}

::google::protobuf::uint8* Param::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClusterService.Param)
  // optional int32 valueInt = 1;
  if (has_valueint()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->valueint(), target);
  }

  // optional int64 valueLong = 2;
  if (has_valuelong()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->valuelong(), target);
  }

  // optional float valueFloat = 3;
  if (has_valuefloat()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->valuefloat(), target);
  }

  // optional double valueDouble = 4;
  if (has_valuedouble()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->valuedouble(), target);
  }

  // optional bool valueBool = 5;
  if (has_valuebool()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->valuebool(), target);
  }

  // optional string valueString = 6;
  if (has_valuestring()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->valuestring().data(), this->valuestring().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ClusterService.Param.valueString");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->valuestring(), target);
  }

  // optional .ClusterService.Param.ValueType type = 7;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      7, this->type(), target);
  }

  // optional string name = 8;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ClusterService.Param.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->name(), target);
  }

  // repeated string valueStringCollection = 9;
  for (int i = 0; i < this->valuestringcollection_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->valuestringcollection(i).data(), this->valuestringcollection(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ClusterService.Param.valueStringCollection");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(9, this->valuestringcollection(i), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ClusterService.Param)
  return target;
}

int Param::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ClusterService.Param)
  int total_size = 0;

  // optional .ClusterService.Param.ValueType type = 7;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // optional string name = 8;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // repeated string valueStringCollection = 9;
  total_size += 1 * this->valuestringcollection_size();
  for (int i = 0; i < this->valuestringcollection_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->valuestringcollection(i));
  }

  switch (valueOneOf_case()) {
    // optional int32 valueInt = 1;
    case kValueInt: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->valueint());
      break;
    }
    // optional int64 valueLong = 2;
    case kValueLong: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->valuelong());
      break;
    }
    // optional float valueFloat = 3;
    case kValueFloat: {
      total_size += 1 + 4;
      break;
    }
    // optional double valueDouble = 4;
    case kValueDouble: {
      total_size += 1 + 8;
      break;
    }
    // optional bool valueBool = 5;
    case kValueBool: {
      total_size += 1 + 1;
      break;
    }
    // optional string valueString = 6;
    case kValueString: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->valuestring());
      break;
    }
    case VALUEONEOF_NOT_SET: {
      break;
    }
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Param::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ClusterService.Param)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Param* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Param>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ClusterService.Param)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ClusterService.Param)
    MergeFrom(*source);
  }
}

void Param::MergeFrom(const Param& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ClusterService.Param)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  valuestringcollection_.MergeFrom(from.valuestringcollection_);
  switch (from.valueOneOf_case()) {
    case kValueInt: {
      set_valueint(from.valueint());
      break;
    }
    case kValueLong: {
      set_valuelong(from.valuelong());
      break;
    }
    case kValueFloat: {
      set_valuefloat(from.valuefloat());
      break;
    }
    case kValueDouble: {
      set_valuedouble(from.valuedouble());
      break;
    }
    case kValueBool: {
      set_valuebool(from.valuebool());
      break;
    }
    case kValueString: {
      set_valuestring(from.valuestring());
      break;
    }
    case VALUEONEOF_NOT_SET: {
      break;
    }
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void Param::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ClusterService.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Param::CopyFrom(const Param& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClusterService.Param)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Param::IsInitialized() const {

  return true;
}

void Param::Swap(Param* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Param::InternalSwap(Param* other) {
  std::swap(type_, other->type_);
  name_.Swap(&other->name_);
  valuestringcollection_.UnsafeArenaSwap(&other->valuestringcollection_);
  std::swap(valueOneOf_, other->valueOneOf_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Param::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Param_descriptor_;
  metadata.reflection = Param_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Param

// optional int32 valueInt = 1;
bool Param::has_valueint() const {
  return valueOneOf_case() == kValueInt;
}
void Param::set_has_valueint() {
  _oneof_case_[0] = kValueInt;
}
void Param::clear_valueint() {
  if (has_valueint()) {
    valueOneOf_.valueint_ = 0;
    clear_has_valueOneOf();
  }
}
 ::google::protobuf::int32 Param::valueint() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueInt)
  if (has_valueint()) {
    return valueOneOf_.valueint_;
  }
  return 0;
}
 void Param::set_valueint(::google::protobuf::int32 value) {
  if (!has_valueint()) {
    clear_valueOneOf();
    set_has_valueint();
  }
  valueOneOf_.valueint_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueInt)
}

// optional int64 valueLong = 2;
bool Param::has_valuelong() const {
  return valueOneOf_case() == kValueLong;
}
void Param::set_has_valuelong() {
  _oneof_case_[0] = kValueLong;
}
void Param::clear_valuelong() {
  if (has_valuelong()) {
    valueOneOf_.valuelong_ = GOOGLE_LONGLONG(0);
    clear_has_valueOneOf();
  }
}
 ::google::protobuf::int64 Param::valuelong() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueLong)
  if (has_valuelong()) {
    return valueOneOf_.valuelong_;
  }
  return GOOGLE_LONGLONG(0);
}
 void Param::set_valuelong(::google::protobuf::int64 value) {
  if (!has_valuelong()) {
    clear_valueOneOf();
    set_has_valuelong();
  }
  valueOneOf_.valuelong_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueLong)
}

// optional float valueFloat = 3;
bool Param::has_valuefloat() const {
  return valueOneOf_case() == kValueFloat;
}
void Param::set_has_valuefloat() {
  _oneof_case_[0] = kValueFloat;
}
void Param::clear_valuefloat() {
  if (has_valuefloat()) {
    valueOneOf_.valuefloat_ = 0;
    clear_has_valueOneOf();
  }
}
 float Param::valuefloat() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueFloat)
  if (has_valuefloat()) {
    return valueOneOf_.valuefloat_;
  }
  return 0;
}
 void Param::set_valuefloat(float value) {
  if (!has_valuefloat()) {
    clear_valueOneOf();
    set_has_valuefloat();
  }
  valueOneOf_.valuefloat_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueFloat)
}

// optional double valueDouble = 4;
bool Param::has_valuedouble() const {
  return valueOneOf_case() == kValueDouble;
}
void Param::set_has_valuedouble() {
  _oneof_case_[0] = kValueDouble;
}
void Param::clear_valuedouble() {
  if (has_valuedouble()) {
    valueOneOf_.valuedouble_ = 0;
    clear_has_valueOneOf();
  }
}
 double Param::valuedouble() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueDouble)
  if (has_valuedouble()) {
    return valueOneOf_.valuedouble_;
  }
  return 0;
}
 void Param::set_valuedouble(double value) {
  if (!has_valuedouble()) {
    clear_valueOneOf();
    set_has_valuedouble();
  }
  valueOneOf_.valuedouble_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueDouble)
}

// optional bool valueBool = 5;
bool Param::has_valuebool() const {
  return valueOneOf_case() == kValueBool;
}
void Param::set_has_valuebool() {
  _oneof_case_[0] = kValueBool;
}
void Param::clear_valuebool() {
  if (has_valuebool()) {
    valueOneOf_.valuebool_ = false;
    clear_has_valueOneOf();
  }
}
 bool Param::valuebool() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueBool)
  if (has_valuebool()) {
    return valueOneOf_.valuebool_;
  }
  return false;
}
 void Param::set_valuebool(bool value) {
  if (!has_valuebool()) {
    clear_valueOneOf();
    set_has_valuebool();
  }
  valueOneOf_.valuebool_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueBool)
}

// optional string valueString = 6;
bool Param::has_valuestring() const {
  return valueOneOf_case() == kValueString;
}
void Param::set_has_valuestring() {
  _oneof_case_[0] = kValueString;
}
void Param::clear_valuestring() {
  if (has_valuestring()) {
    valueOneOf_.valuestring_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_valueOneOf();
  }
}
 const ::std::string& Param::valuestring() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueString)
  if (has_valuestring()) {
    return valueOneOf_.valuestring_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
 void Param::set_valuestring(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueString)
  if (!has_valuestring()) {
    clear_valueOneOf();
    set_has_valuestring();
    valueOneOf_.valuestring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  valueOneOf_.valuestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueString)
}
 void Param::set_valuestring(const char* value) {
  if (!has_valuestring()) {
    clear_valueOneOf();
    set_has_valuestring();
    valueOneOf_.valuestring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  valueOneOf_.valuestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClusterService.Param.valueString)
}
 void Param::set_valuestring(const char* value, size_t size) {
  if (!has_valuestring()) {
    clear_valueOneOf();
    set_has_valuestring();
    valueOneOf_.valuestring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  valueOneOf_.valuestring_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClusterService.Param.valueString)
}
 ::std::string* Param::mutable_valuestring() {
  if (!has_valuestring()) {
    clear_valueOneOf();
    set_has_valuestring();
    valueOneOf_.valuestring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:ClusterService.Param.valueString)
  return valueOneOf_.valuestring_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Param::release_valuestring() {
  // @@protoc_insertion_point(field_release:ClusterService.Param.valueString)
  if (has_valuestring()) {
    clear_has_valueOneOf();
    return valueOneOf_.valuestring_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
 void Param::set_allocated_valuestring(::std::string* valuestring) {
  if (!has_valuestring()) {
    valueOneOf_.valuestring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_valueOneOf();
  if (valuestring != NULL) {
    set_has_valuestring();
    valueOneOf_.valuestring_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        valuestring);
  }
  // @@protoc_insertion_point(field_set_allocated:ClusterService.Param.valueString)
}

// optional .ClusterService.Param.ValueType type = 7;
void Param::clear_type() {
  type_ = 0;
}
 ::ClusterService::Param_ValueType Param::type() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.type)
  return static_cast< ::ClusterService::Param_ValueType >(type_);
}
 void Param::set_type(::ClusterService::Param_ValueType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Param.type)
}

// optional string name = 8;
void Param::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Param::name() const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Param::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ClusterService.Param.name)
}
 void Param::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ClusterService.Param.name)
}
 void Param::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ClusterService.Param.name)
}
 ::std::string* Param::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ClusterService.Param.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Param::release_name() {
  // @@protoc_insertion_point(field_release:ClusterService.Param.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Param::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ClusterService.Param.name)
}

// repeated string valueStringCollection = 9;
int Param::valuestringcollection_size() const {
  return valuestringcollection_.size();
}
void Param::clear_valuestringcollection() {
  valuestringcollection_.Clear();
}
 const ::std::string& Param::valuestringcollection(int index) const {
  // @@protoc_insertion_point(field_get:ClusterService.Param.valueStringCollection)
  return valuestringcollection_.Get(index);
}
 ::std::string* Param::mutable_valuestringcollection(int index) {
  // @@protoc_insertion_point(field_mutable:ClusterService.Param.valueStringCollection)
  return valuestringcollection_.Mutable(index);
}
 void Param::set_valuestringcollection(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:ClusterService.Param.valueStringCollection)
  valuestringcollection_.Mutable(index)->assign(value);
}
 void Param::set_valuestringcollection(int index, const char* value) {
  valuestringcollection_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:ClusterService.Param.valueStringCollection)
}
 void Param::set_valuestringcollection(int index, const char* value, size_t size) {
  valuestringcollection_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:ClusterService.Param.valueStringCollection)
}
 ::std::string* Param::add_valuestringcollection() {
  // @@protoc_insertion_point(field_add_mutable:ClusterService.Param.valueStringCollection)
  return valuestringcollection_.Add();
}
 void Param::add_valuestringcollection(const ::std::string& value) {
  valuestringcollection_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:ClusterService.Param.valueStringCollection)
}
 void Param::add_valuestringcollection(const char* value) {
  valuestringcollection_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:ClusterService.Param.valueStringCollection)
}
 void Param::add_valuestringcollection(const char* value, size_t size) {
  valuestringcollection_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:ClusterService.Param.valueStringCollection)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
Param::valuestringcollection() const {
  // @@protoc_insertion_point(field_list:ClusterService.Param.valueStringCollection)
  return valuestringcollection_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
Param::mutable_valuestringcollection() {
  // @@protoc_insertion_point(field_mutable_list:ClusterService.Param.valueStringCollection)
  return &valuestringcollection_;
}

bool Param::has_valueOneOf() const {
  return valueOneOf_case() != VALUEONEOF_NOT_SET;
}
void Param::clear_has_valueOneOf() {
  _oneof_case_[0] = VALUEONEOF_NOT_SET;
}
Param::ValueOneOfCase Param::valueOneOf_case() const {
  return Param::ValueOneOfCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Params::kAlgoTypeFieldNumber;
const int Params::kGenericParamsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Params::Params()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ClusterService.Params)
}

void Params::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Params::Params(const Params& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:ClusterService.Params)
}

void Params::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  algotype_ = 0;
}

Params::~Params() {
  // @@protoc_insertion_point(destructor:ClusterService.Params)
  SharedDtor();
}

void Params::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Params::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Params::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Params_descriptor_;
}

const Params& Params::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_ClusterService_2eproto();
  return *default_instance_;
}

Params* Params::default_instance_ = NULL;

Params* Params::New(::google::protobuf::Arena* arena) const {
  Params* n = new Params;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Params::Clear() {
// @@protoc_insertion_point(message_clear_start:ClusterService.Params)
  algotype_ = 0;
  genericparams_.Clear();
}

bool Params::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ClusterService.Params)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .ClusterService.AlgoType algoType = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_algotype(static_cast< ::ClusterService::AlgoType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_genericParams;
        break;
      }

      // repeated .ClusterService.Param genericParams = 2;
      case 2: {
        if (tag == 18) {
         parse_genericParams:
          DO_(input->IncrementRecursionDepth());
         parse_loop_genericParams:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_genericparams()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_genericParams;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ClusterService.Params)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ClusterService.Params)
  return false;
#undef DO_
}

void Params::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ClusterService.Params)
  // optional .ClusterService.AlgoType algoType = 1;
  if (this->algotype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->algotype(), output);
  }

  // repeated .ClusterService.Param genericParams = 2;
  for (unsigned int i = 0, n = this->genericparams_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->genericparams(i), output);
  }

  // @@protoc_insertion_point(serialize_end:ClusterService.Params)
}

::google::protobuf::uint8* Params::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ClusterService.Params)
  // optional .ClusterService.AlgoType algoType = 1;
  if (this->algotype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->algotype(), target);
  }

  // repeated .ClusterService.Param genericParams = 2;
  for (unsigned int i = 0, n = this->genericparams_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->genericparams(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:ClusterService.Params)
  return target;
}

int Params::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:ClusterService.Params)
  int total_size = 0;

  // optional .ClusterService.AlgoType algoType = 1;
  if (this->algotype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->algotype());
  }

  // repeated .ClusterService.Param genericParams = 2;
  total_size += 1 * this->genericparams_size();
  for (int i = 0; i < this->genericparams_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->genericparams(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Params::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ClusterService.Params)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const Params* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Params>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ClusterService.Params)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ClusterService.Params)
    MergeFrom(*source);
  }
}

void Params::MergeFrom(const Params& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ClusterService.Params)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  genericparams_.MergeFrom(from.genericparams_);
  if (from.algotype() != 0) {
    set_algotype(from.algotype());
  }
}

void Params::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ClusterService.Params)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Params::CopyFrom(const Params& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ClusterService.Params)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Params::IsInitialized() const {

  return true;
}

void Params::Swap(Params* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Params::InternalSwap(Params* other) {
  std::swap(algotype_, other->algotype_);
  genericparams_.UnsafeArenaSwap(&other->genericparams_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Params::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Params_descriptor_;
  metadata.reflection = Params_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Params

// optional .ClusterService.AlgoType algoType = 1;
void Params::clear_algotype() {
  algotype_ = 0;
}
 ::ClusterService::AlgoType Params::algotype() const {
  // @@protoc_insertion_point(field_get:ClusterService.Params.algoType)
  return static_cast< ::ClusterService::AlgoType >(algotype_);
}
 void Params::set_algotype(::ClusterService::AlgoType value) {
  
  algotype_ = value;
  // @@protoc_insertion_point(field_set:ClusterService.Params.algoType)
}

// repeated .ClusterService.Param genericParams = 2;
int Params::genericparams_size() const {
  return genericparams_.size();
}
void Params::clear_genericparams() {
  genericparams_.Clear();
}
const ::ClusterService::Param& Params::genericparams(int index) const {
  // @@protoc_insertion_point(field_get:ClusterService.Params.genericParams)
  return genericparams_.Get(index);
}
::ClusterService::Param* Params::mutable_genericparams(int index) {
  // @@protoc_insertion_point(field_mutable:ClusterService.Params.genericParams)
  return genericparams_.Mutable(index);
}
::ClusterService::Param* Params::add_genericparams() {
  // @@protoc_insertion_point(field_add:ClusterService.Params.genericParams)
  return genericparams_.Add();
}
::google::protobuf::RepeatedPtrField< ::ClusterService::Param >*
Params::mutable_genericparams() {
  // @@protoc_insertion_point(field_mutable_list:ClusterService.Params.genericParams)
  return &genericparams_;
}
const ::google::protobuf::RepeatedPtrField< ::ClusterService::Param >&
Params::genericparams() const {
  // @@protoc_insertion_point(field_list:ClusterService.Params.genericParams)
  return genericparams_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ClusterService

// @@protoc_insertion_point(global_scope)
