find_library(GRPC_LIBRARY_DIR NAMES grpc)
find_path(GRPC_INCLUDE_DIR NAMES grpc/grpc.h)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(grpc REQUIRED_VARS GRPC_LIBRARY_DIR GRPC_INCLUDE_DIR)
if(GRPC_FOUND)
    message(STATUS "Found grpc include - ${GRPC_INCLUDE_DIR}, GRPC library dir - ${GRPC_LIBRARY_DIR}")
else()
    message(WARNING "grpc not found")
endif()
