find_path(CPPKIN_INCLUDE_DIR NAMES cppkin/cppkin.h PATHS ${PROJECT_DIR}/Third_Party/include NO_DEFAULT_PATH)
find_library(CPPKIN_LIBRARY_DIR NAMES cppkin PATHS ${PROJECT_DIR}/Third_Party/lib NO_DEFAULT_PATH)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(cppkin REQUIRED_VARS CPPKIN_LIBRARY_DIR CPPKIN_INCLUDE_DIR)
if(CPPKIN_FOUND)
    message(STATUS "Found cppkin include - ${CPPKIN_INCLUDE_DIR}, cppkin library dir - ${CPPKIN_LIBRARY_DIR}")
else()
    message(WARNING "cppkin not found")
endif()
